from pathlib import Path
from bs4 import BeautifulSoup
import re,json,hashlib,sys
wd=Path('.'); idx=(wd/'index.html').read_text(); app=(wd/'app.js').read_text(); man=(wd/'manifest.webmanifest').read_text(); sw=(wd/'sw.js').read_text(); checks=[]
def chk(n,c,d=''): checks.append((n,bool(c),d)); print(('PASS ' if c else 'FAIL ')+n+((' — '+d) if d else ''))
soup=BeautifulSoup(idx,'html.parser'); ids=[x.get('id') for x in soup.find_all(attrs={'id':True})]; refs=set(re.findall(r'(?:\$|must)\(["\']([A-Za-z0-9_:-]+)["\']\)',app)); refs.update(re.findall(r'document\.getElementById\(["\']([A-Za-z0-9_:-]+)["\']\)',app)); missing=sorted(refs-set(ids)); m=re.search(r'<script>\n(.*?)\n</script>\n</body>',idx,re.S)
chk('HTML parsed',soup.html is not None); chk('unique IDs',len(ids)==len(set(ids)),f'{len(ids)}'); chk('DOM refs',not missing,str(missing[:8])); chk('inline/app byte-equivalent',bool(m and m.group(1)==app.rstrip('\n')))
chk('version title','APEX SCALP GOD 7.4.0' in idx); chk('app version','APEX_APP_VERSION="APEX-SCALP-GOD-7.4.0"' in app); chk('manifest','APEX SCALP GOD 7.4.0' in man); chk('cache bumped','apex-scalp-god-7-4-0-opportunity-whipsaw-v1' in sw)
chk('same memory journal key','titan_journal_v2' in app); chk('same state key','titan_state_v2' in app); chk('same active signal key','titan_active_signals_v2' in app); chk('same path key','apex_path_ledger_v4' in app); chk('same proof epoch','apex_7_3_fresh_forward_proof_epoch' in app)
chk('4-minute M5 freshness','APEX_TRIGGER_FRESH_MAX_MS=240000' in app); chk('60s displayed command max','APEX_COMMAND_MAX_AGE_MS=60000' in app); chk('anti-chase displacement retained','targetUsed>.35' in app and 'favorableATR>maxFavorableATR' in app and 'adverseATR>maxAdverseATR' in app)
chk('multi-bar extension measured','net3ATR' in app and 'net5ATR' in app and 'extended=net3ATR>=.82||net5ATR>=1.18' in app); chk('RSI squeeze risk','rsiExtreme=dir>0?rsi>=72:rsi<=28' in app); chk('counter-first integrated','c.counterFirstRisk' in app and 'p?.decisionP)>=.60' in app); chk('pullback re-entry recognized','reentryConfirmed=pullbackSeen&&resumeNow' in app); chk('whipsaw hard blocks ENTER','whipsawPass=sg?.trigger?.whipsawBlock!==true' in app and '&&whipsawPass&&' in app); chk('clear whipsaw user action','WAIT — COUNTER MOVE RISK' in app)
chk('proof is tier not low-sample padlock',"c.proofTier=histOK?'VERIFIED':eff>=8?'DEVELOPING':'EARLY'" in app and '&&histOK' not in re.search(r'c\.preFreshFire=.*',app).group(0)); chk('mature negative evidence block','histReject' in app and '!histReject&&c.liveQuality' in app); chk('more opportunities recorded','c.score>=.68' in app and 't.netRR>=1.15' in app)
chk('MT5 conservative cost authority','LIVE MT5 SPREAD + CONSERVATIVE FRICTION BUFFER' in app and 'bufferedMt5' in app); chk('manual broker inputs still priority','strictManual' in app and "source='BROKER INPUTS VERIFIED + BUFFER'" in app)
chk('XAU USD cross-market retained','goldDollarCrossMarket' in app and 'USD/JPY' in app and 'EUR/USD' in app and 'USD/CHF' in app); chk('cross-market not hard inverse','crossSupport' in app and 'crossOppose' in app)
chk('calendar patch absent','NEWS RISK RADAR' not in idx and 'forexfactory' not in app.lower() and 'tradingeconomics' not in app.lower())
rep=json.loads((wd/'AUDIT_1M_740_REPORT.json').read_text()); sha=hashlib.sha256(app.encode()).hexdigest(); chk('1M audit passed',rep.get('passed') is True and rep.get('scenarios')==1_000_000); chk('1M source checksum',rep.get('sourceSha256')==sha)
passed=sum(x[1] for x in checks); out={'version':'APEX-SCALP-GOD-7.4.0','passed':passed==len(checks),'checksPassed':passed,'checksTotal':len(checks),'appSha256':sha,'missingDomRefs':missing,'checks':[{'name':n,'passed':p,'detail':d} for n,p,d in checks]}; (wd/'STATIC_AUDIT_740_REPORT.json').write_text(json.dumps(out,indent=2)); print(json.dumps(out,indent=2)); sys.exit(0 if out['passed'] else 1)
